Xiangshang-Nanhu: {
    shape:image
    icon: https://xiangshan-doc.readthedocs.io/zh_CN/latest/figs/LOGO.png
}

bpu-pipeline:{
    style {
        stroke: blue
        font-color: blue
        fill: white
    }
    
    Predictor: {
        shape: sequence_diagram
        Stage I:{
            FakePredictor:{
                
            }
        }
        Stage II:{

        }
        Stage III:{
            
        }

        Stage I -> Stage II
        Stage II -> Stage III
    }   
}